### PR TITLE
Added option subTxt to search in subelement

### PR DESCRIPTION
**Pull request by acouillier**
I needed to search in a subelement of my li instead of simple li text
So I added an option 'subTxt' which get a selector for children of li where we search
For example, if li contains a span with .info class, you specify {subTxt: '.info'} in options in order to filter with this span content text
Useful for complex li content (but surely slower because of jQuery find() function)

### CODE REVIEW

**Comment by dougmays** [comment]
any advice on how to use this version on a table?

**Comment by awbush** [comment]
Try selecting all the table rows, and use the subTxt option to filter on 'td:first-child'.  I think something like this:

```
$('.search-query').fastLiveFilter('tbody tr', {subTxt: 'td:first-child'});
```

**Comment by dougmays** [comment]
hmm...it's kind of working....it's removing all rows..so its searching but not finding anything. For example i have Smith, Jill in my first column on the first line...and if i search for "smith" all rows go away

**Comment by dougmays** [comment]
got it working!

used this
$('.search-query').fastLiveFilter('tbody', {subTxt: 'td:first-child'});

when i searched the tr's inside the tbody

**Comment by awbush** [comment]
This change has been included in #18 and should behave the same way, except using a "selector" option instead of "subTxt"

**Pull request closed without merging**
