### PR TITLE
Added functionality to allow an ignore class

### PR DESCRIPTION
**Pull request by doolittlece**
You can add an ignore to the options that allows the filter to ignore
children that have that class. The ignore defaults to filter-ignore. To
support this changed to use the jQuery.text() function.
I implemented this to allow the filter to be used on a table and still restrict certain table elements from being included in the filter. There may well be a better way to do this but this gave me what I wanted and I thought it might be useful. This is my first Git pull request so I probably did it wrong and for that I am sorry.

### CODE REVIEW

**Comment by isoceles** [comment]
This doesn't work.

**Comment by doolittlece** [comment]
Could you provide a little more detail? We are using this in production on
three applications without issue. If I knew a little more about what you
are doing it would help greatly with fixing it.

**Comment by isoceles** [comment]
I'm using fastLiveFilter jQuery plugin 1.1.0.

```
$('#inputAssetFilter').fastLiveFilter('#asset_grid', {
        ignore: 'assetCategories'
    });
```

It is still filtering .assetCategories

**Comment by doolittlece** [comment]
The problem I think is that awbush never pulled my changes. The only way to
get the functionality is to pull the version from my fork
https://github.com/doolittlece/jquery-fastLiveFilter if you pull from there
it has the functionality. Please try that and let me know if you are still
having problems.

On Wed, Nov 20, 2013 at 11:23 AM, Chris Doss notifications@github.comwrote:

> I'm using fastLiveFilter jQuery plugin 1.1.0.
> 
> $('#inputAssetFilter').fastLiveFilter('#asset_grid', {
>         ignore: 'assetCategories'
>     });
> 
> It is still filtering .assetCategories
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/awbush/jquery-fastLiveFilter/pull/16#issuecomment-28914612
> .

## 

Thank you,

Casey Doolittle

**Comment by isoceles** [comment]
Yah, that's the one I was using. I pasted it in and it;s still not working. 

.assetCategories is a span that exists in each li.

**Comment by doolittlece** [comment]
Chris,

I am sorry it took so long to reply, work has really been swamping me. I
had a chance to check this over and I don't see an issue. I create a
codenvy factory that demonstrates the functionality that you describe.
Please look at it and let me know if you are unable to get it to work. I
did notice that it seems 1.10 of jquery is incompatible at this time.
Please review the factory and let me know if it helps you get
fastLiveFilter working.

https://codenvy.com/factory?id=05omcj2964q1e437

Thank you,

Casey Doolittle

On Wed, Nov 20, 2013 at 11:35 AM, Chris Doss notifications@github.comwrote:

> Yah, that's the one I was using. I pasted it in and it;s still not
> working.
> 
> .assetCategories is a span that exists in each li.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/awbush/jquery-fastLiveFilter/pull/16#issuecomment-28915648
> .

## 

Thank you,

Casey Doolittle

**Pull request closed without merging**
